### ISSUE TITLE
Unknown function and method estado()

### ISSUE THREAD

**Issue by OmJao** [stevenstc/TRX-Swap-Simple#1]
There's an unknown function and method used in the main index file, because of this all the transactions fail at:

https://github.com/stevenstc/TRX-Swap-Simple/blob/main/src/components/CrowdFunding/index.js

this.estado = this.estado.bind(this);

async estado()

Looks like this code was used on a previous smart contract or React code

**Comment by stevenstc** [comment]
That function is there to update the application that to use the USDT you have to approve the balances to the contract to be able to make exchanges, if you are looking for a simple swap there is this other more complete project

https://github.com/DaLlrium/Brutustoken
